-- Adds the waitlist_signups table for the pre-launch site gate (waiting-list
-- + maintenance mode email capture). Hand-written rather than generated by
-- `prisma migrate dev` for the same reason as every other migration in this
-- history -- see 20260825120000_add_eurostat_data_source's note: the shadow
-- database has no auth schema to replay the auth.users trigger migration
-- against. Applied directly via `mcp__supabase__execute_sql` / `migrate deploy`.

CREATE TABLE "waitlist_signups" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "waitlist_signups_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "waitlist_signups_email_key" ON "waitlist_signups"("email");
