import type { ComponentType, SVGProps } from "react";
import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArrowLeftIcon,
  ArrowLeftOnRectangleIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingDownIcon,
  ArrowTrendingUpIcon,
  ArrowUpCircleIcon,
  ArrowUpIcon,
  ArrowUpTrayIcon,
  ArrowDownIcon,
  ArrowsPointingOutIcon,
  ArrowsRightLeftIcon,
  BellAlertIcon,
  BellIcon,
  BoltIcon,
  BookOpenIcon,
  CalculatorIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardDocumentCheckIcon,
  ClockIcon,
  CloudArrowUpIcon,
  Cog6ToothIcon,
  CpuChipIcon,
  CreditCardIcon,
  DevicePhoneMobileIcon,
  EllipsisHorizontalIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FireIcon,
  FlagIcon,
  FunnelIcon,
  GlobeAltIcon,
  HeartIcon,
  InformationCircleIcon,
  KeyIcon,
  LightBulbIcon,
  LinkSlashIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MegaphoneIcon,
  MinusCircleIcon,
  MinusIcon,
  MoonIcon,
  NewspaperIcon,
  NoSymbolIcon,
  PaperAirplaneIcon,
  PencilIcon,
  PencilSquareIcon,
  PercentBadgeIcon,
  PhotoIcon,
  PlayCircleIcon,
  PlayIcon,
  PlusIcon,
  PresentationChartLineIcon,
  RadioIcon,
  RectangleGroupIcon,
  RocketLaunchIcon,
  RssIcon,
  ScaleIcon,
  ShieldCheckIcon,
  SignalIcon,
  SignalSlashIcon,
  SparklesIcon,
  SquaresPlusIcon,
  Squares2X2Icon,
  Square3Stack3DIcon,
  StarIcon,
  StopCircleIcon,
  SunIcon,
  SwatchIcon,
  TableCellsIcon,
  TagIcon,
  TrashIcon,
  TrophyIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserPlusIcon,
  VariableIcon,
  VideoCameraIcon,
  WifiIcon,
  WrenchScrewdriverIcon,
  XCircleIcon,
  XMarkIcon,
} from "@heroicons/react/24/solid";
import {
  DraftingCompassIcon,
  HandshakeIcon,
  HourglassIcon,
  PremiumBadgeIcon,
  RadioButtonUncheckedIcon,
  RulerIcon,
  SaveIcon,
  TargetIcon,
} from "./custom";

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

// Maps every Material Symbols ligature name previously used in this codebase
// to its Heroicons solid replacement (the vast majority), a hand-wrapped
// Lineicons SVG (./custom.tsx, for concepts Heroicons doesn't cover), or the
// closest semantic substitute for the ~10 icons that exist in neither library
// (candlestick_chart, gavel, target, radar, near_me, psychology, done_all,
// wifi_off, event_busy, add_photo_alternate — noted inline below). Everything
// renders solid/bold — there is no separate outline set in this registry,
// per the "one consistent bold style everywhere" decision.
export const ICON_REGISTRY: Record<string, IconComponent> = {
  // Navigation / arrows
  arrow_back: ArrowLeftIcon,
  arrow_forward: ArrowRightIcon,
  arrow_upward: ArrowUpIcon,
  arrow_downward: ArrowDownIcon,
  arrow_drop_up: ChevronUpIcon,
  arrow_drop_down: ChevronDownIcon,
  chevron_left: ChevronLeftIcon,
  chevron_right: ChevronRightIcon,
  expand_less: ChevronUpIcon,
  expand_more: ChevronDownIcon,
  open_in_new: ArrowTopRightOnSquareIcon,
  open_in_full: ArrowsPointingOutIcon,
  trending_up: ArrowTrendingUpIcon,
  trending_down: ArrowTrendingDownIcon,
  trending_flat: ArrowRightIcon,
  upgrade: ArrowUpCircleIcon,
  login: ArrowLeftOnRectangleIcon,
  logout: ArrowRightOnRectangleIcon,
  near_me: MapPinIcon, // substitute — no "my location/GPS" icon in either library
  sync: ArrowPathIcon,
  sync_alt: ArrowsRightLeftIcon,
  autorenew: ArrowPathIcon,
  refresh: ArrowPathIcon,
  progress_activity: ArrowPathIcon,
  currency_exchange: ArrowsRightLeftIcon,
  upload_file: ArrowUpTrayIcon,
  publish: CloudArrowUpIcon,

  // Status / feedback
  check: CheckIcon,
  check_circle: CheckCircleIcon,
  cancel: XCircleIcon,
  close: XMarkIcon,
  error: ExclamationCircleIcon,
  warning: ExclamationTriangleIcon,
  warning_amber: ExclamationTriangleIcon,
  info: InformationCircleIcon,
  verified: CheckBadgeIcon,
  verified_user: ShieldCheckIcon,
  health_and_safety: ShieldCheckIcon,
  block: NoSymbolIcon,
  done_all: CheckCircleIcon, // substitute — no double-checkmark icon in either library
  radio_button_checked: CheckCircleIcon,
  radio_button_unchecked: RadioButtonUncheckedIcon,

  // Actions
  add: PlusIcon,
  add_task: ClipboardDocumentCheckIcon,
  add_alert: BellAlertIcon,
  add_photo_alternate: PhotoIcon, // substitute — loses the "add" nuance
  edit: PencilIcon,
  edit_note: PencilSquareIcon,
  delete: TrashIcon,
  delete_forever: TrashIcon,
  remove: MinusIcon,
  save: SaveIcon,
  search: MagnifyingGlassIcon,
  search_off: MagnifyingGlassIcon, // substitute — loses the "off" nuance
  send: PaperAirplaneIcon,
  filter_list_off: FunnelIcon,
  more_horiz: EllipsisHorizontalIcon,
  play_arrow: PlayIcon,
  play_circle: PlayCircleIcon,
  play_lesson: PlayCircleIcon,
  stop_circle: StopCircleIcon,
  tune: AdjustmentsHorizontalIcon,
  palette: SwatchIcon,
  calculate: CalculatorIcon,
  check_box: CheckCircleIcon,
  check_box_outline_blank: RadioButtonUncheckedIcon,
  remove_circle: MinusCircleIcon,

  // Visibility / auth
  visibility: EyeIcon,
  visibility_off: EyeSlashIcon,
  lock: LockClosedIcon,
  lock_open: LockOpenIcon,
  lock_reset: LockOpenIcon,
  password: KeyIcon,

  // People / social
  person: UserIcon,
  person_add: UserPlusIcon,
  account_circle: UserCircleIcon,
  manage_accounts: UserCircleIcon,
  group: UserGroupIcon,
  groups: UserGroupIcon,
  groups_3: UserGroupIcon,
  diversity_3: UserGroupIcon,
  handshake: HandshakeIcon,
  chat: ChatBubbleLeftIcon,
  chat_bubble: ChatBubbleLeftIcon,
  chat_bubble_outline: ChatBubbleLeftIcon,
  forum: ChatBubbleLeftRightIcon,
  reviews: ChatBubbleLeftRightIcon,
  favorite: HeartIcon,

  // Comms
  notifications: BellIcon,
  notifications_active: BellAlertIcon,
  mail: EnvelopeIcon,
  email: EnvelopeIcon,
  mark_email_read: EnvelopeOpenIcon,
  rss_feed: RssIcon,
  campaign: MegaphoneIcon,
  podcasts: RadioIcon,
  newspaper: NewspaperIcon,
  link_off: LinkSlashIcon,
  wifi_off: SignalSlashIcon, // substitute — no "wifi off/slash" icon in either library
  phone_android: DevicePhoneMobileIcon,
  smartphone: DevicePhoneMobileIcon,

  // Time / scheduling
  schedule: ClockIcon,
  history: ClockIcon,
  calendar_today: CalendarIcon,
  calendar_month: CalendarDaysIcon,
  event: CalendarIcon,
  event_busy: CalendarDaysIcon, // substitute — loses the "busy" nuance
  today: CalendarIcon,
  hourglass_empty: HourglassIcon,
  hourglass_disabled: HourglassIcon,

  // Finance / trading
  candlestick_chart: ChartBarIcon, // substitute — no candlestick-chart icon in either library
  bar_chart: ChartBarIcon,
  analytics: ChartBarIcon,
  show_chart: PresentationChartLineIcon,
  ssid_chart: PresentationChartLineIcon,
  monitoring: PresentationChartLineIcon,
  space_dashboard: Squares2X2Icon,
  schema: RectangleGroupIcon,
  grid_on: TableCellsIcon,
  table_rows: TableCellsIcon,
  percent: PercentBadgeIcon,
  sell: TagIcon,
  credit_card: CreditCardIcon,
  functions: VariableIcon,
  target: TargetIcon,
  radar: SignalIcon, // substitute — no radar icon in either library

  // Academy / achievements
  school: AcademicCapIcon,
  menu_book: BookOpenIcon,
  auto_stories: BookOpenIcon,
  checklist: ClipboardDocumentCheckIcon,
  rule: ScaleIcon,
  gavel: ScaleIcon, // substitute — no gavel/legal icon in either library
  balance: ScaleIcon,
  leaderboard: TrophyIcon,
  military_tech: TrophyIcon,
  workspace_premium: PremiumBadgeIcon,
  local_fire_department: FireIcon,
  rocket_launch: RocketLaunchIcon,
  tips_and_updates: LightBulbIcon,
  lightbulb: LightBulbIcon,
  auto_awesome: SparklesIcon,
  psychology: LightBulbIcon, // substitute — no brain/psychology icon in either library
  robot_2: CpuChipIcon,
  architecture: DraftingCompassIcon,
  straighten: RulerIcon,
  construction: WrenchScrewdriverIcon,

  // Misc
  public: GlobeAltIcon,
  location_on: MapPinIcon,
  photo_camera: CameraIcon,
  videocam: VideoCameraIcon,
  format_list_bulleted: ListBulletIcon,
  flag: FlagIcon,
  flag_2: FlagIcon,
  star: StarIcon,
  dark_mode: MoonIcon,
  light_mode: SunIcon,
  settings: Cog6ToothIcon,
  wifi: WifiIcon,
  squares_plus: SquaresPlusIcon,
  bolt: BoltIcon,
  layers: Square3Stack3DIcon,
};

export type IconName = keyof typeof ICON_REGISTRY;
